// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEdMkQRdr0cYrpzS_JawHK-AaGZYTY8c4',
    appId: '1:1092627765402:web:533c925b690817d0a7e723',
    messagingSenderId: '1092627765402',
    projectId: 'hackathon-fall-2022',
    authDomain: 'hackathon-fall-2022.firebaseapp.com',
    storageBucket: 'hackathon-fall-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPDRJX9p-NnDhQ7gfmpqTV_bY53qRomc',
    appId: '1:1092627765402:android:56a9905a8cc73d44a7e723',
    messagingSenderId: '1092627765402',
    projectId: 'hackathon-fall-2022',
    storageBucket: 'hackathon-fall-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOL6tHGMzoKcVPfz3iYXvS8qd_vQADlkw',
    appId: '1:1092627765402:ios:fd182bf584a1f3a7a7e723',
    messagingSenderId: '1092627765402',
    projectId: 'hackathon-fall-2022',
    storageBucket: 'hackathon-fall-2022.appspot.com',
    iosClientId: '1092627765402-p6bco0enr6falai0l7kbprar3okogc4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceGate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOL6tHGMzoKcVPfz3iYXvS8qd_vQADlkw',
    appId: '1:1092627765402:ios:fd182bf584a1f3a7a7e723',
    messagingSenderId: '1092627765402',
    projectId: 'hackathon-fall-2022',
    storageBucket: 'hackathon-fall-2022.appspot.com',
    iosClientId: '1092627765402-p6bco0enr6falai0l7kbprar3okogc4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceGate',
  );
}
